# when training the keys here will be relabeld to the values, can be used to merge multiple species into a single label
# i.e red and yellow parekeets into parakeet
RELABEL_MAP = {
    "gragoo1": "cangoo",
    "mallar3": "x00458",
    "domesz3tic-chicken": "redjun1",
    "yeepen1": "litpen1",
    "yefpar3": "parake",
    "refpar4": "parake",
    "nezrob2": "nezrob3",
    "redpol1": "comred",
}


# add labels you want regardless of number of samples
# birds from all birds will be added if they have over 50 records and 2 validation samples
BIRD_TRAIN_LABELS = [
    "ausbit1",
    "ausmag2",
    "baicra4",
    "blkswa",
    "eurbla",
    "fernbi1",
    "gryger1",
    "houspa",
    "kiwi",
    "morepo2",
    "nezfan1",
    "redjun",
    "silver3",
    "sonthr1",
    "tui1",
    "y01193",
]


ALL_BIRDS = [
    "ausbit1",
    "ausmag2",
    "auspip3",
    "aussho1",
    "baicra4",
    "barpar2",
    "bird",
    "blbgul1",
    "blfter1",
    "blknod",
    "blkswa",
    "bluduc1",
    "brncre",
    "bubrai1",
    "calqua",
    "cangoo",
    "categr1",
    "charob1",
    "chiger2",
    "chukar",
    "codpet1",
    "comcha",
    "commyn",
    "compea",
    "comred",
    "coopet",
    "criros2",
    "dobplo1",
    "domesz3tic-chicken",
    "dove",
    "dunnoc1",
    "easros1",
    "eurbla",
    "eurcoo",
    "eurgol",
    "eurgre1",
    "eursta",
    "fernbi1",
    "gragoo1",
    "gretea1",
    "grwpet2",
    "gryger1",
    "houspa",
    "hutshe1",
    "kea1",
    "kelgul",
    "kiwi",
    "kokako3",
    "litowl1",
    "litpen1",
    "lotkoe1",
    "mallar3",
    "masboo",
    "maslap1",
    "morepo2",
    "motpet",
    "nezbel1",
    "nezfal1",
    "nezfan1",
    "nezkak1",
    "nezpig2",
    "nezpig3",
    "nezrob2",
    "nezrob3",
    "noiger1",
    "noipar1",
    "norfolk silkeye",
    "oyster1",
    "pacrob2",
    "parake",
    "parpet1",
    "parshe1",
    "piesti1",
    "purswa6",
    "rebgul1",
    "redjun",
    "redpol1",
    "refpar4",
    "rettro",
    "riflem1",
    "rinphe1",
    "rocpig",
    "rocwre",
    "rook1",
    "royalb2",
    "sackin1",
    "sbweye1",
    "shbcuc1",
    "silver3",
    "skylar",
    "soioys1",
    "sonthr1",
    "sooshe",
    "sooter1",
    "sopsku1",
    "spocra1",
    "spocra2",
    "stitch1",
    "swahar1",
    "tomtit1",
    "tui1",
    "varoys1",
    "weka1",
    "welswa1",
    "weta",
    "whcalb1",
    "whfher1",
    "whfter1",
    "whiteh1",
    "whiter",
    "wiltur",
    "x00458",
    "y01193",
    "yeepen1",
    "yefpar3",
    "yellow2",
    "yellow3",
]

# NOISE SECTION
NOISE_LABELS = [
    "Acoustic_guitar",
    "Bass_guitar",
    "Clapping",
    "Coin_(dropping)",
    "Crash_cymbal",
    "Dishes_and_pots_and_pans",
    "Engine",
    "Fart",
    "Fire",
    "Fireworks",
    "Glass",
    "Hi-hat",
    "Piano",
    "Rain",
    "Slam",
    "Squeak",
    "Tearing",
    "Walk_or_footsteps",
    "Wind",
    "Writing",
    "airplane",
    "beach",
    "breathing",
    "brown",
    "brushing_teeth",
    "campfire",
    "can_opening",
    "car_horn",
    "chainsaw",
    "chirping_birds",
    "church_bells",
    "city",
    "clapping",
    "clock_alarm",
    "clock_tick",
    "construction",
    "crackling_fire",
    "door_wood_creaks",
    "door_wood_knock",
    "drinking_sipping",
    "engine",
    "factory",
    "fan",
    "fireworks",
    "footsteps",
    "forest",
    "glass_breaking",
    "hand_saw",
    "helicopter",
    "insect",
    "keyboard_typing",
    "library",
    "mouse_click",
    "noise",
    "planecabin",
    "pouring_water",
    "rain",
    "rainforest",
    "river",
    "sea_waves",
    "siren",
    "snoring",
    "starship",
    "static",
    "thunderstorm",
    "toilet_flush",
    "train",
    "vacuum_cleaner",
    "vehicle",
    "washing_machine",
    "water",
    "water_drops",
    "white",
    "wind",
]

ANIMAL_LABELS = [
    "bear",
    "cat",
    "chicken",
    "cow",
    "dog",
    "dolphin",
    "donkey",
    "elephant",
    "frog",
    "hen",
    "horse",
    "lion",
    "monkey",
    "pig",
    "possum",
    "rodent",
    "sheep",
]

INSECT_LABELS = ["crickets", "insects"]

HUMAN_LABELS = [
    "Breathing",
    "Coughing",
    "Crying baby",
    "Laughing",
    "Sneezing",
    "coughing",
    "crying_baby",
    "laughing",
    "sneezing",
]


EXTRA_LABELS = ["rooster", "frog", "insect", "human", "noise"]
OTHER_LABELS = []


for l in NOISE_LABELS:
    if l != "noise":
        RELABEL_MAP[l] = "noise"


for l in HUMAN_LABELS:
    if l != "human":
        RELABEL_MAP[l] = "human"


for l in OTHER_LABELS:
    if l != "other":
        RELABEL_MAP[l] = "other"
