MERGE_LABELS = {
    "gragoo1": "cangoo",
    "mallar3": "x00458",
    "domesz3tic-chicken": "redjun1",
    "yeepen1": "litpen1",
    "yefpar3": "parake",
    "refpar4": "parake",
    "nezrob2": "nezrob3",
    "redpol1": "comred",
}


# add labels you want regardless of number of samples
# birds from all birds will be added if they have over 50 records and 2 validation samples
BIRD_TRAIN_LABELS = [
    "ausbit1",
    "ausmag2",
    "baicra4",
    "blkswa",
    "eurbla",
    "fernbi1",
    "gryger1",
    "houspa",
    "kiwi",
    "morepo2",
    "nezfan1",
    "redjun",
    "silver3",
    "sonthr1",
    "tui1",
    "y01193",
]


ALL_BIRDS = [
    "ausbit1",
    "ausmag2",
    "auspip3",
    "aussho1",
    "baicra4",
    "barpar2",
    "bird",
    "blbgul1",
    "blfter1",
    "blknod",
    "blkswa",
    "bluduc1",
    "brncre",
    "bubrai1",
    "calqua",
    "cangoo",
    "categr1",
    "charob1",
    "chiger2",
    "chukar",
    "codpet1",
    "comcha",
    "commyn",
    "compea",
    "comred",
    "coopet",
    "criros2",
    "dobplo1",
    "domesz3tic-chicken",
    "dove",
    "dunnoc1",
    "easros1",
    "eurbla",
    "eurcoo",
    "eurgol",
    "eurgre1",
    "eursta",
    "fernbi1",
    "gragoo1",
    "gretea1",
    "grwpet2",
    "gryger1",
    "houspa",
    "hutshe1",
    "kea1",
    "kelgul",
    "kiwi",
    "kokako3",
    "litowl1",
    "litpen1",
    "lotkoe1",
    "mallar3",
    "masboo",
    "maslap1",
    "morepo2",
    "motpet",
    "nezbel1",
    "nezfal1",
    "nezfan1",
    "nezkak1",
    "nezpig2",
    "nezpig3",
    "nezrob2",
    "nezrob3",
    "noiger1",
    "noipar1",
    "norfolk silkeye",
    "oyster1",
    "pacrob2",
    "parake",
    "parpet1",
    "parshe1",
    "piesti1",
    "purswa6",
    "rebgul1",
    "redjun",
    "redpol1",
    "refpar4",
    "rettro",
    "riflem1",
    "rinphe1",
    "rocpig",
    "rocwre",
    "rook1",
    "royalb2",
    "sackin1",
    "sbweye1",
    "shbcuc1",
    "silver3",
    "skylar",
    "soioys1",
    "sonthr1",
    "sooshe",
    "sooter1",
    "sopsku1",
    "spocra1",
    "spocra2",
    "stitch1",
    "swahar1",
    "tomtit1",
    "tui1",
    "varoys1",
    "weka1",
    "welswa1",
    "weta",
    "whcalb1",
    "whfher1",
    "whfter1",
    "whiteh1",
    "whiter",
    "wiltur",
    "x00458",
    "y01193",
    "yeepen1",
    "yefpar3",
    "yellow2",
    "yellow3",
]
# ALL_BIRDS = [
#     "crow",
#     "new zealand fantail",
#     "australian magpie",
#     "bellbird",
#     "bird",
#     "black noddy",
#     "blackbird",
#     "california quail",
#     "canada goose",
#     "common starling",
#     "crimson rosella",
#     "dunnock",
#     "fantail",
#     "grey warbler",
#     "goldfinch",
#     "house sparrow",
#     "kiwi",
#     "little owl",
#     "magpie",
#     "morepork",
#     "norfolk gerygone",
#     "norfolk parrot",
#     "norfolk robin",
#     "norfolk silvereye",
#     "north island robin",
#     "parakeet",
#     "red-crowned parakeet",
#     "rifleman",
#     "robin",
#     "sacred kingfisher",
#     "silvereye",
#     "slender-billed white-eye",
#     "song thrush",
#     "sooty tern",
#     "sparrow",
#     "spur-winged plover",
#     "starling",
#     "thrush",
#     "tui",
#     "whistler",
#     "white tern",
#     "australasian bittern",
#     "banded dotterel",
#     "brown creeper",
#     "chaffinch",
#     "common pheasant",
#     "dove",
#     "eastern rosella",
#     "eurasian blackbird",
#     "european goldfinch",
#     "european greenfinch",
#     "greenfinch",
#     "gull",
#     "harrier",
#     "kaka",
#     "kea",
#     "kereru",
#     "kingfisher",
#     "masked booby",
#     "norfolk silkeye",
#     "owl",
#     "paradise shelduck",
#     "pheasant",
#     "pigeon",
#     "red-tailed tropicbird",
#     "redpoll",
#     "rosella",
#     "southern black-backed gull",
#     "swamp harrier",
#     "tomtit",
#     "turkey",
#     "yellowhammer",
#     "australasian bittern",
#     "australasian-harrier",
#     "australasian-shoveler",
#     "australian magpie",
#     "banded dotterel",
#     "barbary-partridge",
#     "bellbird",
#     "black-billed-gull",
#     "black-fronted-tern",
#     "black-petrel",
#     "black-swan",
#     "blackbird",
#     "blue-whio",
#     "brown-creeper",
#     "buff-banded-rail",
#     "california-quail",
#     "canada-goose",
#     "chaffinch",
#     "chatham-island-warbler",
#     "chatham-islands-pigeon",
#     "chatham-robin",
#     "chukor",
#     "common-diving-petrel",
#     "common-pheasant",
#     "cook's-petrel",
#     "domesz3tic-chicken",
#     "dunnock",
#     "eastern-rosella",
#     "eurasian-coot",
#     "fantail",
#     "goldfinch",
#     "gray-faced-petrel",
#     "graylag-goose-(domestic-type)",
#     "greenfinch",
#     "grey warbler",
#     "grey-or-mallard-duck",
#     "grey-teal",
#     "gull",
#     "house sparrow",
#     "hutton's-shearwater",
#     "indian-myna",
#     "kea",
#     "kereru",
#     "kiwi",
#     "little-blue-penguin",
#     "little-owl",
#     "long-tailed-cuckoo",
#     "mallard-duck",
#     "marsh-crake",
#     "mohua",
#     "morepork",
#     "mottled-petrel",
#     "new-zealand-falcon",
#     "new-zealand-fernbird",
#     "new-zealand-kaka",
#     "new-zealand-kingfisher",
#     "new-zealand-pipit",
#     "north-island-kokako",
#     "north-island-robin",
#     "oystercatcher",
#     "paradise-shelduck",
#     "parakeet",
#     "peafowl",
#     "pied-stilt",
#     "pukeko",
#     "red-billed-gull",
#     "red-crowned-parakeet",
#     "redpoll",
#     "rifleman",
#     "rock-wren",
#     "shining-cuckoo",
#     "silvereye",
#     "skylark",
#     "song thrush",
#     "sooty-shearwater",
#     "south-island-oystercatcher",
#     "south-island-robin",
#     "south-polar-skua",
#     "southern-black-backed-gull",
#     "southern-royal-albatross",
#     "spotless-crake",
#     "spotted-crake",
#     "spur-winged-plover",
#     "starling",
#     "stitchbird",
#     "tomtit",
#     "tree-weta",
#     "tui",
#     "variable-oystercatcher",
#     "weka",
#     "welcome-swallow",
#     "western-cattle-egret",
#     "white-capped-albatross",
#     "white-faced-heron",
#     "white-fronted-tern",
#     "whitehead",
#     "wild-turkey",
#     "yellow-crowned-parakeet",
#     "yellow-eyed-penguin",
#     "yellowhammer",
#     "yellowhead"
# ]

# NOISE SECTION
NOISE_LABELS = [
    "insect",
    "wind",
    "vehicle",
    "rain",
    "static",
    "noise",
    "water",
]

OTHER_NOISE = [
    "Acoustic_guitar",
    "Bass_guitar",
    "Clapping",
    "Coin_(dropping)",
    "Crash_cymbal",
    "Dishes_and_pots_and_pans",
    "Engine",
    "Fart",
    "Fire",
    "Fireworks",
    "Glass",
    "Hi-hat",
    "Piano",
    "Rain",
    "Slam",
    "Squeak",
    "Tearing",
    "Walk_or_footsteps",
    "Wind",
    "Writing",
    "beach",
    "brown",
    "campfire",
    "city",
    "construction",
    "engine",
    "factory",
    "fan",
    "forest",
    "library",
    "planecabin",
    "rain",
    "rainforest",
    "river",
    "starship",
    "static",
    "thunderstorm",
    "train",
    "water",
    "white",
    "wind",
]

OTHER_NOISE.extend(
    [
        "airplane",
        "breathing",
        "brushing_teeth",
        "can_opening",
        "car_horn",
        "chainsaw",
        "chirping_birds",
        "church_bells",
        "clapping",
        "clock_alarm",
        "clock_tick",
        "crackling_fire",
        "door_wood_creaks",
        "door_wood_knock",
        "drinking_sipping",
        "engine",
        "fireworks",
        "footsteps",
        "glass_breaking",
        "hand_saw",
        "helicopter",
        "keyboard_typing",
        "mouse_click",
        "pouring_water",
        "rain",
        "sea_waves",
        "siren",
        "snoring",
        "thunderstorm",
        "toilet_flush",
        "train",
        "vacuum_cleaner",
        "washing_machine",
        "water_drops",
        "wind",
    ]
)


NOISE_LABELS.extend(OTHER_NOISE)

NOISE_LABELS = list(set(NOISE_LABELS))
NOISE_LABELS.sort()


ANIMAL_LABELS = [
    "bear",
    "cat",
    "chicken",
    "cow",
    "dog",
    "dolphin",
    "donkey",
    "elephant",
    "frog",
    "horse",
    "lion",
    "monkey",
    "possum",
    "rodent",
    "sheep",
    "pig",
    "hen",
]

INSECT_LABELS = ["crickets", "insects"]

HUMAN_LABELS = [
    "Crying baby",
    "Sneezing",
    "Breathing",
    "Coughing",
    "Laughing",
    "crying_baby",
    "sneezing",
    "laughing",
    "coughing",
]

EXTRA_LABELS = ["rooster", "frog", "insect", "human", "noise"]
OTHER_LABELS = []


# MERGE_LABELS = {
# "house sparrow":"houspa",
# "new zealand fantail":"nezfan1",
# "australian magpie":"ausmag2",
# "norfolk silvereye":"silver3",
# "graylag-goose-(domestic-type)":"cangoo",
# "canada-goose":"cangoo",
# "grey-or-mallard-duck":"x00458",
# "mallard-duck":"x00458",
# "california-quail":"calqua",
# "domesz3tic-chicken":"redjun1",
# "yellow-eyed-penguin":"litpen1",
# "little-blue-penguin":"litpen1",
# "yellow-crowned-parakeet":"parake",
# "red-crowned parakeet":"parake",
# "red-crowned-parakeet":"parake",
# "brown-creeper":"brncre",
# "north-island-robin":"nezrob3",
# "north island robin":"nezrob3",
# "south-island-robin":"nezrob3",
# "south island robin":"nezrob3",
# "mohua":"yellow3",
# "new-zealand-kingfisher":"sackin1",
# "kingfisher":"sackin1",
# "kingfisher":"sackin1",
# }
